package com.djenkins.fitness.domain;

import java.time.Instant;
import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.PastOrPresent;
import javax.validation.constraints.PositiveOrZero;
import javax.validation.constraints.Size;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@Entity
@Table(name = "fitness_week")
@ApiModel(description = "Class representing a week of physical exercise.")
public class FitnessWeek {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "week_id")
	@ApiModelProperty(
			notes = "Unique identifier of the FitnessWeek. No two weeks can have the same id. This is generated by the system on creation.",
			example = "1",
			required = false,
			position = 0)
	private Long id;

	@ApiModelProperty(
			notes = "The number of minutes of exercise done this week.",
			example = "120",
			required = true,
			position = 1)
	@Column(name = "total_time")
	@PositiveOrZero
	@NotNull
	private Long totalTime;

	@ApiModelProperty(
			notes = "The number of miles traveled this week if applicable.",
			example = "30.4",
			required = true,
			position = 2)
	@Column(name = "total_miles")
	@PositiveOrZero
	@NotNull
	private Double totalMiles;

	@ApiModelProperty(
			notes = "The number of calories burned this week.",
			example = "300.5",
			required = true,
			position = 3)
	@Column(name = "total_calories")
	@PositiveOrZero
	@NotNull
	private Double totalCalories;

	@ApiModelProperty(
			notes = "The number of miles exercised to date if applicable. Rounded down to nearest whole number.",
			example = "250",
			required = true,
			position = 4)
	@Column(name = "miles_to_date")
	@PositiveOrZero
	@NotNull
	private Long milesToDate;

	@ApiModelProperty(
			notes = "The days that exercise was done this week.",
			example = "M/T/W",
			required = true,
			position = 5)
	@Column(name = "days_exercised")
	@NotBlank
	@Size(max=20)
	private String daysExercised;

	@ApiModelProperty(
			notes = "The date that the exercise was recorded, normally the last day of the week that exercise took place.",
			example = "2020-03-20",
			required = true,
			position = 6)
	@Column(name = "date_recorded")
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
	@DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
	@NotNull
	@PastOrPresent
	private LocalDate dateRecorded;

	@ApiModelProperty(
			notes = "The type of exercise done this week.",
			example = "Cycling",
			required = true,
			position = 7)
	@Column(name = "exercise_type")
	@NotBlank
	@Size(max=20)
	private String exerciseType;

	@ApiModelProperty(
			notes = "The timestamp that the week was added to the system. Will be generated by the system on creation.",
			example = "2020-03-20 06:43:19.769",
			required = false,
			position = 8)
	@Column(name = "created_date")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "UTC")
	@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
	private Instant createdTs;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getTotalTime() {
		return totalTime;
	}

	public void setTotalTime(Long totalTime) {
		this.totalTime = totalTime;
	}

	public Double getTotalMiles() {
		return totalMiles;
	}

	public void setTotalMiles(Double totalMiles) {
		this.totalMiles = totalMiles;
	}

	public Double getTotalCalories() {
		return totalCalories;
	}

	public void setTotalCalories(Double totalCalories) {
		this.totalCalories = totalCalories;
	}

	public Long getMilesToDate() {
		return milesToDate;
	}

	public void setMilesToDate(Long milesToDate) {
		this.milesToDate = milesToDate;
	}

	public String getDaysExercised() {
		return daysExercised;
	}

	public void setDaysExercised(String daysExercised) {
		this.daysExercised = daysExercised;
	}

	public LocalDate getDateRecorded() {
		return dateRecorded;
	}

	public void setDateRecorded(LocalDate dateRecorded) {
		this.dateRecorded = dateRecorded;
	}

	public String getExerciseType() {
		return exerciseType;
	}

	public void setExerciseType(String exerciseType) {
		this.exerciseType = exerciseType;
	}

	public Instant getCreatedTs() {
		return createdTs;
	}

	public void setCreatedTs(Instant createdTs) {
		this.createdTs = createdTs;
	}

}
