package com.djenkins.fitness.domain;

import java.sql.Date;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@Entity
@Table(name = "fitness_week")
@ApiModel(description = "Class representing a week of physical exercise.")
public class FitnessWeek {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "week_id")
	@ApiModelProperty(
			notes = "Unique identifier of the FitnessWeek. No two weeks can have the same id. This is generated by the system on creation.",
			example = "1",
			required = false,
			position = 0)
	private Long id;

	@ApiModelProperty(
			notes = "The number of minutes of exercise done this week.",
			example = "120",
			required = true,
			position = 1)
	@Column(name = "total_time")
	private Long totalTime;

	@ApiModelProperty(
			notes = "The number of miles traveled this week if applicable.",
			example = "30.4",
			required = true,
			position = 2)
	@Column(name = "total_miles")
	private Double totalMiles;

	@ApiModelProperty(
			notes = "The number of calories burned this week.",
			example = "300.5",
			required = true,
			position = 3)
	@Column(name = "total_calories")
	private Double totalCalories;

	@ApiModelProperty(
			notes = "The number of miles exercised to date if applicable. Rounded down to nearest whole number.",
			example = "250",
			required = true,
			position = 4)
	@Column(name = "miles_to_date")
	private Long milesToDate;

	@ApiModelProperty(
			notes = "The days that exercise was done this week.",
			example = "M/T/W",
			required = true,
			position = 5)
	@Column(name = "days_exercised")
	private String daysExercised;

	@ApiModelProperty(
			notes = "The date that the exercise was recorded, normally the last day of the week that exercise took place.",
			example = "2020-03-20",
			required = true,
			position = 6)
	@Column(name = "date_recorded")
	private Date dateRecorded;

	@ApiModelProperty(
			notes = "The type of exercise done this week.",
			example = "Cycling",
			required = true,
			position = 7)
	@Column(name = "exercise_type")
	private String exerciseType;

	@ApiModelProperty(
			notes = "The timestamp that the week was added to the system. Will be generated by the system on creation.",
			example = "2020-03-20 06:43:19.769",
			required = false,
			position = 8)
	@Column(name = "created_date")
	private Timestamp createdTs;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getTotalTime() {
		return totalTime;
	}

	public void setTotalTime(Long totalTime) {
		this.totalTime = totalTime;
	}

	public Double getTotalMiles() {
		return totalMiles;
	}

	public void setTotalMiles(Double totalMiles) {
		this.totalMiles = totalMiles;
	}

	public Double getTotalCalories() {
		return totalCalories;
	}

	public void setTotalCalories(Double totalCalories) {
		this.totalCalories = totalCalories;
	}

	public Long getMilesToDate() {
		return milesToDate;
	}

	public void setMilesToDate(Long milesToDate) {
		this.milesToDate = milesToDate;
	}

	public String getDaysExercised() {
		return daysExercised;
	}

	public void setDaysExercised(String daysExercised) {
		this.daysExercised = daysExercised;
	}

	public Date getDateRecorded() {
		return dateRecorded;
	}

	public void setDateRecorded(Date dateRecorded) {
		this.dateRecorded = dateRecorded;
	}

	public String getExerciseType() {
		return exerciseType;
	}

	public void setExerciseType(String exerciseType) {
		this.exerciseType = exerciseType;
	}

	public Timestamp getCreatedTs() {
		return createdTs;
	}

	public void setCreatedTs(Timestamp createdTs) {
		this.createdTs = createdTs;
	}

}
